#!/usr/bin/env bash
# Provision Cloudflare R2 bucket + API token for StrawWU direct ISO CDN.
# Requires a Cloudflare API token with: Account.R2 (Edit), Zone.DNS (Edit) for strawwu.org.
#
# Usage:
#   export STRAWWU_CF_API_TOKEN='...'   # strawwu.org account token
#   export STRAWWU_CF_ACCOUNT_ID='...'  # optional if token is account-scoped
#   ./scripts/setup-iso-cdn-r2.sh
#
# After success, copy scripts/iso-cdn.env.example → scripts/iso-cdn.env and run publish.
set -euo pipefail

ACCOUNT_ID="${STRAWWU_CF_ACCOUNT_ID:-}"
TOKEN="${STRAWWU_CF_API_TOKEN:-${CLOUDFLARE_API_TOKEN:-}}"
BUCKET="${STRAWWU_ISO_S3_BUCKET:-strawwu-releases}"
ZONE_NAME="${STRAWWU_ZONE_NAME:-strawwu.org}"
CDN_HOST="${STRAWWU_ISO_CDN_HOST:-pub-5f85d511d7344db2be8308026a082b13.r2.dev}"
OUT_ENV="$(dirname "$0")/iso-cdn.env"

[[ -n "$TOKEN" ]] || { echo "Set STRAWWU_CF_API_TOKEN (strawwu.org Cloudflare account)" >&2; exit 1; }

cf_api() {
  local method="$1" path="$2" body="${3:-}"
  if [[ -n "$body" ]]; then
    curl -fsS -X "$method" -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" \
      -d "$body" "https://api.cloudflare.com/client/v4${path}"
  else
    curl -fsS -X "$method" -H "Authorization: Bearer $TOKEN" \
      "https://api.cloudflare.com/client/v4${path}"
  fi
}

if [[ -z "$ACCOUNT_ID" ]]; then
  ACCOUNT_ID="$(cf_api GET "/accounts?per_page=1" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d["result"][0]["id"])')"
fi

echo "Account: $ACCOUNT_ID"

if ! cf_api GET "/accounts/${ACCOUNT_ID}/r2/buckets/${BUCKET}" >/dev/null 2>&1; then
  echo "Creating R2 bucket: $BUCKET"
  cf_api POST "/accounts/${ACCOUNT_ID}/r2/buckets" "{\"name\":\"${BUCKET}\"}" >/dev/null
else
  echo "R2 bucket exists: $BUCKET"
fi

# Enable public r2.dev subdomain for whole-file downloads
cf_api PUT "/accounts/${ACCOUNT_ID}/r2/buckets/${BUCKET}/domains/managed" '{"enabled":true}' >/dev/null || true
MANAGED_DOMAIN="$(cf_api GET "/accounts/${ACCOUNT_ID}/r2/buckets/${BUCKET}/domains/managed" \
  | python3 -c 'import json,sys; d=json.load(sys.stdin); print((d.get("result") or {}).get("domain") or "")' 2>/dev/null || true)"
if [[ -n "$MANAGED_DOMAIN" ]]; then
  CDN_HOST="$MANAGED_DOMAIN"
fi

S3_ENDPOINT="https://${ACCOUNT_ID}.r2.cloudflarestorage.com"

# Preserve existing S3 keys if present
EXISTING_ACCESS=''
EXISTING_SECRET=''
if [[ -f "$OUT_ENV" ]]; then
  # shellcheck disable=SC1090
  source "$OUT_ENV" || true
  EXISTING_ACCESS="${STRAWWU_ISO_S3_ACCESS_KEY:-}"
  EXISTING_SECRET="${STRAWWU_ISO_S3_SECRET_KEY:-}"
fi

cat > "$OUT_ENV" <<EOF
# Generated by setup-iso-cdn-r2.sh
# CF management token stays in ~/.hermes/.env only (latest STRAWWU_CF_API_TOKEN).
export STRAWWU_CF_ACCOUNT_ID='${ACCOUNT_ID}'
export STRAWWU_ISO_S3_ENDPOINT='${S3_ENDPOINT}'
export STRAWWU_ISO_S3_BUCKET='${BUCKET}'
export STRAWWU_ISO_S3_PREFIX='releases'
export STRAWWU_ISO_CDN_BASE='https://${CDN_HOST}'
export STRAWWU_ISO_S3_ACCESS_KEY='${EXISTING_ACCESS:-REPLACE_ME}'
export STRAWWU_ISO_S3_SECRET_KEY='${EXISTING_SECRET:-REPLACE_ME}'
EOF
chmod 600 "$OUT_ENV"

cat <<EOF

R2 bucket ready: ${BUCKET}
S3 endpoint: ${S3_ENDPOINT}
Public CDN: https://${CDN_HOST}

Next (dashboard → R2 → Manage API Tokens → Create Object Read & Write on ${BUCKET}):
1. Paste Access Key ID + Secret Access Key into ${OUT_ENV}
2. Publish whole ISO (no split):
   source ${OUT_ENV}
   ./scripts/publish-github-release.sh 0.7.0.13
   ./scripts/generate-manifest.sh && git add docs/r2-releases docs/releases.json && git commit -m "..." && git push

Note: custom domain download.strawwu.org needs the strawwu.org zone on this same CF account.

EOF
