#!/usr/bin/env bash
# Provision Cloudflare R2 bucket + API token for StrawWU direct ISO CDN.
# Requires a Cloudflare API token with: Account.R2 (Edit), Zone.DNS (Edit) for strawwu.org.
#
# Usage:
#   export STRAWWU_CF_API_TOKEN='...'   # strawwu.org account token
#   export STRAWWU_CF_ACCOUNT_ID='...'  # optional if token is account-scoped
#   ./scripts/setup-iso-cdn-r2.sh
#
# After success, copy scripts/iso-cdn.env.example → scripts/iso-cdn.env and run publish.
set -euo pipefail

ACCOUNT_ID="${STRAWWU_CF_ACCOUNT_ID:-}"
TOKEN="${STRAWWU_CF_API_TOKEN:-${CLOUDFLARE_API_TOKEN:-}}"
BUCKET="${STRAWWU_ISO_S3_BUCKET:-strawwu-releases}"
ZONE_NAME="${STRAWWU_ZONE_NAME:-strawwu.org}"
CDN_HOST="${STRAWWU_ISO_CDN_HOST:-download.strawwu.org}"
OUT_ENV="$(dirname "$0")/iso-cdn.env"

[[ -n "$TOKEN" ]] || { echo "Set STRAWWU_CF_API_TOKEN (strawwu.org Cloudflare account)" >&2; exit 1; }

cf_api() {
  local method="$1" path="$2" body="${3:-}"
  if [[ -n "$body" ]]; then
    curl -fsS -X "$method" -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" \
      -d "$body" "https://api.cloudflare.com/client/v4${path}"
  else
    curl -fsS -X "$method" -H "Authorization: Bearer $TOKEN" \
      "https://api.cloudflare.com/client/v4${path}"
  fi
}

if [[ -z "$ACCOUNT_ID" ]]; then
  ACCOUNT_ID="$(cf_api GET "/accounts?per_page=1" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d["result"][0]["id"])')"
fi

echo "Account: $ACCOUNT_ID"

if ! cf_api GET "/accounts/${ACCOUNT_ID}/r2/buckets/${BUCKET}" >/dev/null 2>&1; then
  echo "Creating R2 bucket: $BUCKET"
  cf_api POST "/accounts/${ACCOUNT_ID}/r2/buckets" "{\"name\":\"${BUCKET}\"}" >/dev/null
else
  echo "R2 bucket exists: $BUCKET"
fi

# Create scoped R2 token via Cloudflare dashboard is preferred; document manual step if API unavailable.
S3_ENDPOINT="https://${ACCOUNT_ID}.r2.cloudflarestorage.com"

cat > "$OUT_ENV" <<EOF
# Generated by setup-iso-cdn-r2.sh — fill in access keys from Cloudflare R2 → Manage API tokens
export STRAWWU_ISO_S3_ENDPOINT='${S3_ENDPOINT}'
export STRAWWU_ISO_S3_BUCKET='${BUCKET}'
export STRAWWU_ISO_S3_PREFIX='releases'
export STRAWWU_ISO_CDN_BASE='https://${CDN_HOST}'
export STRAWWU_ISO_S3_ACCESS_KEY='REPLACE_ME'
export STRAWWU_ISO_S3_SECRET_KEY='REPLACE_ME'
EOF
chmod 600 "$OUT_ENV"

cat <<EOF

R2 bucket ready: ${BUCKET}
S3 endpoint: ${S3_ENDPOINT}

Next steps (strawwu.org Cloudflare dashboard):
1. R2 → ${BUCKET} → Settings → Public access OR Custom Domain → ${CDN_HOST}
   (Custom domain replaces tunnel to Hermes build machine — do NOT mirror ISO on build host.)
2. R2 → Manage R2 API Tokens → Create token (Object Read & Write) → paste keys into:
   ${OUT_ENV}
3. If using custom domain, set DNS for ${CDN_HOST} per R2 wizard (remove tunnel CNAME).
4. Publish ISO:
   source ${OUT_ENV}
   ./scripts/publish-github-release.sh 0.6.2.5
   ./scripts/generate-manifest.sh

EOF
